version: '3.4'

services:
  seatarranger.com.console:
    image: ${DOCKER_REGISTRY}seatarrangercomconsole
    build:
      context: .
      dockerfile: src/seatarranger.com.Console/Dockerfile

  seatarranger.com:
    image: ${DOCKER_REGISTRY}seatarrangercom
    build:
      context: .
      dockerfile: src/seatarranger.com/Dockerfile


  seatarranger.com.core.tests:
    image: ${DOCKER_REGISTRY}seatarrangercomcoretests
    build:
      context: .
      dockerfile: src/seatarranger.com.Core.Tests/Dockerfile

